sudo: false

os:
  - linux

language:
  - python

python:
  - "2.7"

services:
  - docker

before_script:
  - docker build -t elbenfreund:hamster-gtk-devel .

script:
    # See: https://docs.codecov.io/docs/testing-with-docker for details
  - ci_env=`bash <(curl -s https://codecov.io/env)`
  - docker run $ci_env elbenfreund:hamster-gtk-devel ./run_docker.sh
